// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDXhOWI_w16m_3BMRX0BKGfk4mYyTUGD8',
    appId: '1:433988052170:web:2af94a1ab985d435bb0033',
    messagingSenderId: '433988052170',
    projectId: 'mealy-a9de6',
    authDomain: 'mealy-a9de6.firebaseapp.com',
    storageBucket: 'mealy-a9de6.appspot.com',
    measurementId: 'G-BZHFDNQLDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCutjcNIAbXEM5AeFCKxHOVw1Y6IjzmKZc',
    appId: '1:433988052170:android:2830be88da731958bb0033',
    messagingSenderId: '433988052170',
    projectId: 'mealy-a9de6',
    storageBucket: 'mealy-a9de6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASOsDdMFT7gf6PmXquV708fQxmUBfgMhQ',
    appId: '1:433988052170:ios:c5dff0212b63ac15bb0033',
    messagingSenderId: '433988052170',
    projectId: 'mealy-a9de6',
    storageBucket: 'mealy-a9de6.appspot.com',
    iosClientId: '433988052170-bjmiaf3daridel6uh4ukphtf31sogaur.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealy',
  );
}
